### ISSUE TITLE
Does not work on iOS5beta6 / iPad2

### ISSUE THREAD

**Issue by stroendle** [GoranHalvarsson/BarcodeReader-MonoTouch#1]
Hi Goran,

thanks for your great work. Your work is appreciated very much.

We are using your library inside a project as a QR-code-reader and it works perfect (while not being as fast as red-laser ;-))

Today I updated my iPad2 to iOS 5 beta 6 (before it was a iOS 4.3-device).
On the iPad our application and your test-client do no longer work. The application comes to a stop after displaying the overlay.
The code seems to hang at:

```
            //The iris - we don't want that one
            NSNotificationCenter.DefaultCenter.AddObserver(new NSString("PLCameraViewIrisAnimationDidEndNotification"), (notification) => {   

                if(this.View != null)
                {
                    _imageView.RemoveFromSuperview();

                    this.OverlayView.StartWorker();
                }
            });  
```

If I disable the "iris"-code and simple remove to image and start the overlayview-worker, the camera image is shown, but a few times each second a "Exception of type 'com.google.zxing.ReaderException' was thrown." is thrown.
I did not find the source to this error.

We are still some time away from iOS 5 release, but it would be great, if you had a look into that issue.

Best greetings from Germany

Stefan

**Comment by stroendle** [comment]
Update: I have downgraded my iPad2 to iOS 4.3.5.

_The iris-problem is gone, so this seems to be definitely an iOS 5 issue._

But the exception com.google.zxing.ReaderException persists, so I cannot scan any barcodes on the iPad2, independent of the iOS-Version.

**Comment by GoranHalvarsson** [comment]
Hello
I'm glad that you guys are using it.
I will take look and try to fix it for IOS 5.
I will let you know when it's fixed.
Br
Göran

Skickat från min iPhone

20 aug 2011 kl. 13:35 skrev stroendlereply@reply.github.com:

**Comment by GoranHalvarsson** [comment]
Hello

I have not upgraded it for IOS5... But the error com.google.zxing.ReaderException, it occurs at 
BarcodeReader-MonoTouch / BarcodeTesting / Controllers / CameraOverLayView.cs in row 200. And it's suppose to do that.  I have not tested it on iPad2. 

Br
Goran

**Comment by ric3kg** [comment]
Thanks for all this great work. I've used your example to add scanning to my app. But it only works on an iPhone, not my iPad 2. Any thoughts on getting the iPad to see a bar code?

Thanks,
Rick

**Comment by GoranHalvarsson** [comment]
Hello

I will take a look on this iPad2 issue, as soon as I have an iPad2.

**Comment by ric3kg** [comment]
It looks like the problem is the device - there does not seem to be support for non-auto focus cameras. The iPad 2 and iPod Touch are both non-auto focus, so there does not seem to be a work around. But, if you figure one out, I'd love to hear about it!

**Comment by reistiago** [comment]
Hi,

the problem for custom overlay is that the notification "PLCameraViewIrisAnimationDidEndNotification" is no longer used on iOS 5.

I didn't managed to find any replacement for this, for now at least I'm not showing the custom overlay, and I'm showing the default Iris. @GoranHalvarsson, unless you want I'm not submitting a patch for this since my solution is mostly to delete code ;) But if you want it please let me know.

**Comment by GoranHalvarsson** [comment]
Hello

Tank you for clearing it out. Yes I agree, no patch. Lets wait until we find a solution how to hide the iris in iOS 5. 
I'm glad that you are using it. :-)

Br
Göran

**Comment by stroendle** [comment]
Hi there,

I think I have found the problem which is preventing the software to run on an iPad2.
It is, in my opinion, a bug of MonoTouch.
I have filed it at http://bugzilla.xamarin.com/show_bug.cgi?id=1894

Best,

Stefan

**Comment by GoranHalvarsson** [comment]
Hello

I hope that they will fix the bug.

Br
Göran

Skickat från min iPhone

5 nov 2011 kl. 12:44 skrev stroendlereply@reply.github.com:
